account/urls.py
from django.urls import path

from account.views import register_user, login_user, logout_admin

app_name = "account"

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_admin, name='logout'),
    path('register/', register_user, name='register'),
    

    # path('success_confrimed/<custom_user_id>/<int:code_send>/', ConfrimUserSuccessView.as_view(), name='Confrim_User_success'),

    # path('ResentCode/<custom_user_id>/', ResentCode.as_view(), name='resent_code'),
    # path('confrimed_user_success', Confrim_User_success, name='Confrim_User_success'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),
    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import login_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace="account")),
    path('', include('phone_book.urls', namespace="phone_book")),
    path('', login_user, name="application")
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager
import uuid
from django.apps import apps
from django.contrib.auth.hashers import make_password
from random import randint
from django.utils import timezone
from extensions.utils import get_filename_ext


def generate_ranint():
    return randint(100000, 999999)


def upload_to_Image_file(instance, filename):
    name, ext = get_filename_ext(filename)
    return f"users/images/{instance.username}/{instance.username}{ext}"


def upload_to_Ticket_file(instance, filename):
    name, ext = get_filename_ext(filename)
    return f"panel/ticket/{instance.user.username}/{instance.title}{ext}"


class CustomUserManager(UserManager):

    def get_familier(self, familier_code):
        """get user with familier_code"""
        try:
            user = self.get(familier_code=familier_code)
            return user
        except:
            return None

    def _create_user(self, username, password, email=None, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')

        selcted_user = self.get_familier(extra_fields["familier_code"])

        if selcted_user is not None:
            extra_fields["familier"] = selcted_user

        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name)
        username = GlobalUserModel.normalize_username(username)
        user = self.model(
            username=username, email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        # str(uuid.uuid4())[-1:8:-1] is a 24 random character
        extra_fields.setdefault('custom_user_id', str(uuid.uuid4())[:11:-1])
        extra_fields.setdefault('familier_code', str(uuid.uuid4())[:8])
        extra_fields.setdefault('gender', "m")
        extra_fields.setdefault('pass_per_save', password or "")
        extra_fields.setdefault('code_send', generate_ranint())
        extra_fields.setdefault('email_sended', False)
        return self._create_user(username, password, **extra_fields)

    def _create_super_user(self, username, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not username:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        GlobalUserModel = apps.get_model(self.model._meta.app_label, self.model._meta.object_name)
        username = GlobalUserModel.normalize_username(username)
        user = self.model(username=username, email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('pass_per_save', password or "")
        extra_fields.setdefault('custom_user_id', str(uuid.uuid4())[:11:-1])
        extra_fields.setdefault('familier_code', str(uuid.uuid4())[:8])
        extra_fields.setdefault('gender', "m")
        extra_fields.setdefault('code_send', generate_ranint())
        extra_fields.setdefault('email_sended', False)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_super_user(username, email, password, **extra_fields)


class USER(AbstractUser):
    familier_code = models.CharField(
        verbose_name="کد معرفی", max_length=8, null=True, blank=True
    )
    familier = models.ForeignKey(
        'self', on_delete=models.SET_NULL, verbose_name="معرف", null=True, blank=True
    )
    pass_per_save = models.CharField(
        verbose_name="گذر واژه هش نشده", max_length=255, blank=True
    )
    GENDER_CHOICES = (
        ("m", "مرد"),
        ("w", "زن"),
        ("b", "ترجیح می دهم نگویم"),
    )
    gender = models.CharField(
        verbose_name="جنسیت", max_length=1, null=False,
        blank=False, choices=GENDER_CHOICES, default="m"
    )
    avatar = models.ImageField(
        verbose_name="آواتار", upload_to=upload_to_Image_file, null=True,
        blank=True, default="None"
    )
    phone_number = models.CharField(
        verbose_name="شماره همراه", max_length=11, null=True, blank=True, unique=True
    )
    custom_user_id = models.CharField(
        verbose_name="کد اختصاصی کاربر", max_length=24, null=True, blank=True, unique=True
    )
    code_send = models.IntegerField(
        verbose_name="کد ارسال شده", null=True, blank=True
    )
    email_sended = models.BooleanField(
        default=False, verbose_name="ایمیل ارسال شده است"
    )
    objects = CustomUserManager()

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        if self.first_name != "" or self.last_name != "":
            full_name = '%s %s' % (self.first_name, self.last_name)
            return full_name.strip()
        else:
            full_name = '%s' % (self.username, )
            return full_name.strip()

account/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.db.models import Q

User = get_user_model()


class LoginForm(forms.Form):
    username = forms.CharField(
        max_length=200,
        label="",
        widget=forms.TextInput(
            attrs={
                "name": "username",
                "id": "username",
                "placeholder": "UserName",
                "dir": "rtl",
            }
        ))
    password = forms.CharField(
        max_length=100,
        label="",
        widget=forms.PasswordInput(
            attrs={
                "name": "password",
                "id": "password",
                "placeholder": "Password",
                "dir": "rtl",
            }
        ))

    def clean_username(self):
        username = self.cleaned_data.get("username")
        user = User.objects.filter(username=username)
        if not user:
            raise forms.ValidationError(
                "نام کاربری صحیح نمی باشد دوباره امتحان کنید")
        else:
            return username

    def clean_password(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = User.objects.filter(username=username, pass_per_save=password)
        if not user:
            raise forms.ValidationError(
                "رمز عبور صحیح نمی باشد دوباره امتحان کنید")
        else:
            return password


class SingUpForm(forms.Form):
    username = forms.CharField(
        max_length=200,
        label="",
        widget=forms.TextInput(
            attrs={
                "name": "username",
                "id": "username",
                "placeholder": "UserName",
                "dir": "rtl",
            }
        ))
    # first_name = forms.CharField(
    #     max_length=200,
    #     label="",
    #     widget=forms.TextInput(
    #         attrs={"class": "input--style-4", "id": "first_name"}
    #     ))
    # last_name = forms.CharField(
    #     max_length=200,
    #     label="",
    #     widget=forms.TextInput(
    #         attrs={"class": "input--style-4", "id": "last_name"}
    #     ))
    # email = forms.CharField(
    #     max_length=300,
    #     label="",
    #     widget=forms.EmailInput(
    #         attrs={"name": "email", "class": "input--style-4",
    #                "id": "email"}
    #     ))
    password = forms.CharField(
        max_length=100,
        label="",
        widget=forms.PasswordInput(
            attrs={
                "name": "password",
                "id": "password",
                "placeholder": "Password",
                "dir": "rtl",
            }
        ))
    password_confirm = forms.CharField(
        max_length=100,
        label="",
        widget=forms.PasswordInput(
            attrs={
                "name": "password",
                "id": "password",
                "placeholder": "Password Confrim",
                "dir": "rtl",
            }
        ))
    # familier = forms.CharField(
    #     max_length=8,
    #     label="",
    #     required=False,
    #     widget=forms.TextInput(
    #         attrs={"type": "text", "class": "input--style-4", "id": "familier_code"}
    #     ))
    # phone_number = forms.CharField(
    #     max_length=11,
    #     label="",
    #     widget=forms.TextInput(attrs={
    #         "type": "tel", "pattern": "^(\+989)+\d{9}$|^(09)+\d{9}$",
    #         "class": "input--style-4", "id": "phone"}
    #     ))

    # def clean_familier(self):
    #     familier_code = self.cleaned_data.get("familier")
    #     if not familier_code:
    #         return familier_code
    #     else:
    #         user_check = User.objects.filter(familier_code=familier_code)
    #         if not user_check:
    #             raise forms.ValidationError(
    #                 "کد معرف یافت نشد خالی رها کرده یا اصلاح نمایید")
    #         return familier_code

    # def clean_phone_number(self):
    #     phone_number = self.cleaned_data.get("phone_number")
    #     user_check = User.objects.filter(phone_number=phone_number)
    #     if user_check:
    #         raise forms.ValidationError(
    #             "این شماره همراه قبلا ثبت نام کرده است")
    #     else:
    #         return phone_number

    # def clean_email(self):
    #     email = self.cleaned_data.get("email")
    #     user_check = User.objects.filter(email=email)
    #     if user_check:
    #         raise forms.ValidationError(
    #             "فردی با این ایمیل ثبت نام کرده است")
    #     else:
    #         return email

    def clean_username(self):
        username = self.cleaned_data.get("username")
        user_check = User.objects.filter(username=username)
        if user_check:
            raise forms.ValidationError(
                "نام کاربری انتخابی از قبل موجود است با نام دیگری دوباره امتحان کنید")
        else:
            return username

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password_confirm != password:
            raise forms.ValidationError(
                "تکرار رمز عبور صحیح نمی باشد لطفا بررسی نمایید")
        else:
            return password_confirm

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import Group
from django.contrib.auth import get_user_model, login, authenticate, logout

from account.forms import SingUpForm, LoginForm

from phone_book.models import BookOwner

User = get_user_model()

redirect_path = "/books"

def login_user(request):
    global redirect_path
    if request.user.is_authenticated:
        return redirect(redirect_path)
    form = LoginForm(request.POST or None)
    if request.POST:
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(request, username=username, password=password)
            # BookOwner.objects.get_or_create(
            #     user = user,
            #     status = True,
            #     is_deleted = False,
            # )
            login(request, user=user)
            return redirect(redirect_path)

    context = {
        "form": form
    }
    return render(request, "login.html", context)


def register_user(request):
    global redirect_path
    if request.user.is_authenticated:
        return redirect(redirect_path)
    form = SingUpForm(request.POST or None)
    er_message = ""
    if request.POST:
        if form.is_valid():
            username = form.cleaned_data.get("username")
            # first_name = form.cleaned_data.get("first_name")
            # last_name = form.cleaned_data.get("last_name")
            # email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            # familier = form.cleaned_data.get("familier")
            # phone = form.cleaned_data.get("phone_number")
            try:
                user = User.objects.create_user(
                    username=username, password=password
                )
                BookOwner.objects.get_or_create(
                    user = user,
                    status = True,
                    is_deleted = False,
                )
                login(request, user)
                return redirect(redirect_path)
            except:
                er_message = "مشکلی وجود دارد لطفا از راه های ارتباطی به ما اطلاع بدهید"

    context = {
        "form": form,
        "er_message": er_message
    }
    return render(request, "register.html", context)


def logout_admin(request):
    global redirect_path
    logout(request)
    return redirect(redirect_path)

account/templates/login.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>ورود به حساب</title>
</head>
<body>
<!-- partial:index.partial.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 1rem;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
button:hover{
    background-color: #98cf93;
}
.err {
    color:red;
    text-align:right;
    margin-top:10px;
    background-color:#55bd94;
    padding:5px;
    border-radius: 0px 5px 0px 5px;
}
.h4style{
    text-align: center;
    margin-top: 1rem;
    padding: 5px;
    border: aqua 2px solid;
    border-radius: 0px 7px 0px 7px;
    background-color: darkblue;
}

.h4style:hover {
    background-color: #297a66;
}

.linkstyle:link {
    text-decoration: none;
}

.linkstyle:visited {
    text-decoration: none;
}

.linkstyle:hover {
    text-decoration: underline;
}

.linkstyle:active {
    text-decoration: underline;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        {% csrf_token %}
        <h3>وارد شوید</h3>

        <label style="float:right;margin-bottom:5px" for="username">نام کاربری</label>
        {{form.username}}
        {% for err in form.username.errors %}
            <p class="err">{{ err }}</p>
        {% endfor %}
        <label style="float:right;margin-bottom:5px" for="password">رمز عبور</label>
        {{form.password}}
        {% for err in form.password.errors %}
            <p class="err">{{ err }}</p>
        {% endfor %}
        <button type="submit">ورود به حساب</button>
        <a class="linkstyle" href="{% url 'account:register' %}"><h4 class="h4style">برای ثبت نام کلیک کنید</h4></a>
    </form>
</body>
</html>
<!-- partial -->
</body>
</html>

account/templates/register.html
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title>ورود به حساب</title>
</head>
<body>
<!-- partial:index.partial.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 1rem;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
button:hover{
    background-color: #98cf93;
}
.err {
    color:red;
    font-weight: bold;
    text-align:right;
    background-color:#55bd94;
    padding:2px;
    margin:3px;
    border-radius: 0px 5px 0px 5px;
}
.h4style{
    text-align: center;
    margin-top: 1rem;
    padding: 5px;
    border: aqua 2px solid;
    border-radius: 0px 7px 0px 7px;
    background-color: darkblue;
}

.h4style:hover {
    background-color: #297a66;
}

.linkstyle:link {
    text-decoration: none;
}

.linkstyle:visited {
    text-decoration: none;
}

.linkstyle:hover {
    text-decoration: underline;
}

.linkstyle:active {
    text-decoration: underline;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        {% csrf_token %}
        <h3>وارد شوید</h3>

        <label style="float:right;" for="username">نام کاربری</label>
        {{form.username}}
        {% for err in form.username.errors %}
            <p class="err">{{ err }}</p>
        {% endfor %}
        <label style="float:right;" for="password">رمز عبور</label>
        {{form.password}}
        {% for err in form.password.errors %}
            <p class="err">{{ err }}</p>
        {% endfor %}
        <label style="float:right;" for="password">تکرار رمز عبور</label>
        {{form.password_confirm}}
        {% for err in form.password_confirm.errors %}
            <p class="err">{{ err }}</p>
            {% endfor %}
        <button type="submit">ثبت نام</button>
        {% if er_message %}<p class="err">{{ er_message }}</p>{% endif %}
        <a class="linkstyle" href="{% url 'account:login' %}"><h4 class="h4style">برای ورود به حساب کلیک کنید</h4></a>
    </form>
</body>
</html>
<!-- partial -->
</body>
</html>