account/urls.py
from django.urls import path

from account.views import register_user, login_user, logout_admin

app_name = "account"

urlpatterns = [
    path('login/', login_user, name='login'),
    path('logout/', logout_admin, name='logout'),
    path('register/', register_user, name='register'),
    

    # path('success_confrimed/<custom_user_id>/<int:code_send>/', ConfrimUserSuccessView.as_view(), name='Confrim_User_success'),

    # path('ResentCode/<custom_user_id>/', ResentCode.as_view(), name='resent_code'),
    # path('confrimed_user_success', Confrim_User_success, name='Confrim_User_success'),
    # path('logout/', views.LogoutView.as_view(), name='logout'),
    # path('password_change/', views.PasswordChangeView.as_view(), name='password_change'),
    # path('password_change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    # path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    # path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    # path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    # path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import login_user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls', namespace="account")),
    path('', include('phone_book.urls', namespace="phone_book")),
    path('', login_user, name="application")
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

phone_book/urls.py
from django.urls import path
from phone_book.views import profile, phone_book_view, add_phone_book, del_phone_book, search_phone_book

app_name = "phone_book"

urlpatterns = [
    path("profile", profile, name="profile"),
    path("books", phone_book_view, name="books"),
    path("books/add_phone_book", add_phone_book, name="add_books"),
    path("books/del_phone_book", del_phone_book, name="del_books"),
    path("books/search_phone_book", search_phone_book, name="search_books"),
]

phone_book/models.py
from django.db import models
from account.models import USER
from extensions.utils import get_filename_ext
from django.db.models import Q


def avatar_uploadTo(instance, fileName):
    name, ext = get_filename_ext(fileName)
    return f"avatars/{name}{ext}"


class Avatar(models.Model):
    avatar = models.ImageField("آواتار", upload_to=avatar_uploadTo, blank=False, null=False, default="None.jpg")
    alt = models.CharField(
        "متن جایگزین تصویر", max_length=255, blank=True, null=True, default="",
        help_text="اگر تصویر به هر دلیل ممکن لود نشود این متن به جای تصویر نمایش داده خواهد شد"
    )
    status = models.BooleanField("فعال/غیر فعال", null=False, blank=False, default=True, 
        help_text="مشخص کنید در صورت فعال بودن قابل انتخاب خواهد بود برای خارج کردن از دسترس غیر فعال نمایید"
    )
    is_deleted = models.BooleanField("فعال/غیر فعال", null=True, blank=True, default=False, 
        editable=False
    )
    
    class Meta:
        verbose_name = "1-"+"آواتار"
        verbose_name_plural = "1-"+"آواتار"


class BookPhone(models.Model):
    name = models.CharField(
        "نام فرد", max_length=255, blank=False, null=False, default="",
    )
    last_name = models.CharField(
        "نام خانوادگی فرد", max_length=255, blank=False, null=False, default="",
    )
    phone_number = models.CharField(
        "شماره همراه فرد", max_length=13, blank=False, null=False, default="",
    )
    phone_number_1 = models.CharField(
        "شماره تلفن فرد", max_length=13, blank=True, null=True, default="",
    )
    avatar = models.ForeignKey(Avatar, blank=True, null=True, default="", on_delete=models.DO_NOTHING, verbose_name="آواتار")
    post = models.CharField(
        "شغل یا سمت فرد", max_length=255, blank=True, null=True, default="",
    )
    is_deleted = models.BooleanField("فعال/غیر فعال", null=True, blank=True, default=False, 
        editable=False
    )

    class Meta:
        verbose_name = "2-"+"مخاطب"
        verbose_name_plural = "2-"+"مخاطب"


class BookOwner(models.Model):
    user = models.ForeignKey(USER, blank=True, null=True, default="", on_delete=models.DO_NOTHING, verbose_name="کاربر")
    avatar = models.ForeignKey(Avatar, blank=True, null=True, default="", on_delete=models.DO_NOTHING, verbose_name="آواتار")
    status = models.BooleanField("فعال/غیر فعال", null=False, blank=False, default=True, 
        help_text="مشخص کنید در صورت فعال بودن کاربر مجاز خواهد بود برای خارج کردن از دسترس غیر فعال نمایید"
    )
    is_deleted = models.BooleanField("فعال/غیر فعال", null=True, blank=True, default=False, 
        editable=False
    )
    
    class Meta:
        verbose_name = "3-"+"کاربر های من"
        verbose_name_plural = "3-"+"کاربر های من"


class Book_UserManager(models.Manager):
    def get_all_books_by_user_or_none(self, user):
        try:
            return self.get_queryset().filter(
                book_owner__user=user, book_owner__status=True,
                book_phone__is_deleted=False, status=True, is_deleted=False,
            )
        except:
            return None

    def get_all_product_filterd_or_none(self, user, query):
        try:
            return self.get_queryset().filter(
                Q(book_phone__name__icontains=query)|Q(book_phone__last_name__icontains=query)|
                Q(book_phone__phone_number__startswith=query)|Q(book_phone__phone_number_1__startswith=query)|
                Q(book_phone__post__icontains=query),book_owner__user=user, book_owner__status=True,
                book_phone__is_deleted=False, status=True, is_deleted=False,
            ).distinct()
        except:
            return None


class Book_User(models.Model):
    book_owner = models.ForeignKey(BookOwner, blank=False, null=False, on_delete=models.DO_NOTHING, verbose_name="کاربر")
    book_phone = models.ForeignKey(BookPhone, blank=False, null=False, on_delete=models.DO_NOTHING, verbose_name="مخاطب")
    status = models.BooleanField("فعال/غیر فعال", null=False, blank=False, default=True, 
        help_text="مشخص کنید در صورت فعال بودن قابل انتخاب خواهد بود برای خارج کردن از دسترس غیر فعال نمایید"
    )
    is_deleted = models.BooleanField("فعال/غیر فعال", null=True, blank=True, default=False, 
        editable=False
    )

    objects = Book_UserManager()
    
    class Meta:
        verbose_name = "انتساب شماره به کاربر"
        verbose_name_plural = "انتساب شماره به کاربر"

phone_book/views.py
from django.shortcuts import render, redirect
from django.template import loader
from django.http import JsonResponse
from phone_book.models import BookPhone, Book_User, BookOwner, Avatar


def profile(request):
    if not request.user.is_authenticated:
        return redirect("/")
    user = request.user
    book_owner = BookOwner.objects.filter(user=user).first()
    avatars = Avatar.objects.filter(
        status = True,
        is_deleted = False,
    )
    if request.POST:
        try:
            first_name = request.POST.get("first_name")
            last_name = request.POST.get("last_name")
            avatar_id = int(request.POST.get("selectedAvatar"))
            avatar = Avatar.objects.filter(pk=avatar_id).first()
            user.first_name = first_name
            user.last_name = last_name
            book_owner.avatar = avatar
            user.save()
            book_owner.save()
        except:
            pass

    context = {
        "avatars":avatars,
        "object":book_owner,
        "book_owner":book_owner,
    }
    return render(request, "profile.html", context)


def phone_book_view(request):
    if not request.user.is_authenticated:
        return redirect("/")
    user = request.user
    book_owner = BookOwner.objects.filter(user=user).first()
    avatars = Avatar.objects.filter(
        status = True,
        is_deleted = False,
    )
    all_product = Book_User.objects.get_all_books_by_user_or_none(request.user)
    context = {
        "avatars":avatars,
        "book_owner":book_owner,
        "object_list":all_product,
    }
    return render(request, "contact_directory.html", context)


def get_all_contact(request):
    if request.user.is_anonymous:
        output_data = {
            'posts_html': None,
        }
        return output_data
    
    all_product = Book_User.objects.get_all_books_by_user_or_none(request.user)
    posts_html = loader.render_to_string(
        'AllContacts.html',
        {'object_list': all_product}
    )
    output_data = {
        'posts_html': posts_html,
    }
    return output_data


def add_phone_book(request):
    try:
        user = request.user
        book_owner = BookOwner.objects.filter(user=user).first()

        name = request.POST.get('name')
        last_name = request.POST.get('last_name')
        phone_number = request.POST.get('phone_number')
        phone_number_1 = request.POST.get('phone_number_1')
        avatar_id = request.POST.get('avatar_id')
        post = request.POST.get('post')

        is_deleted = False

        avatar = Avatar.objects.filter(pk=avatar_id).first()

        book_phone, st = BookPhone.objects.get_or_create(
            name=name,
            last_name=last_name,
            phone_number=phone_number,
            phone_number_1=phone_number_1,
            avatar=avatar,
            post=post,
            is_deleted=is_deleted,
        )

        Book_User.objects.get_or_create(
            book_owner = book_owner,
            book_phone = book_phone,
            status = True,
            is_deleted = False,
        )

        status = True
    except:
        status = False
    posts_html = get_all_contact(request)["posts_html"]
    output_data = {
        'status': status,
        'posts_html': posts_html,
    }
    return JsonResponse(output_data)


def del_phone_book(request):
    try:
        user = request.user
        book_owner = BookOwner.objects.filter(user=user).first()

        try:
            el_id = int(request.POST.get('el_id'))
            book_user = Book_User.objects.get(
                pk=el_id, book_owner=book_owner, is_deleted=False, status=True
            )
            book_user.is_deleted = True
            book_user.save()

            status = True
        except:
            status = False
    except:
        status = False
    posts_html = get_all_contact(request)["posts_html"]
    output_data = {
        'status': status,
        'posts_html': posts_html,
    }
    return JsonResponse(output_data)


def search_phone_book(request):
    query = request.POST.get('query')
    all_product = Book_User.objects.get_all_books_by_user_or_none(request.user)
    all_product_filterd = Book_User.objects.get_all_product_filterd_or_none(request.user, query)
    if query is None:
        posts_html = loader.render_to_string(
            'AllContacts.html',
            {'object_list': all_product}
        )
    else:
        posts_html = loader.render_to_string(
            'AllContacts.html',
            {'object_list': all_product_filterd}
        )
    output_data = {
        'posts_html': posts_html,
    }
    return JsonResponse(output_data)

phone_book/templates/AllContacts.html
{% for object in object_list %}
<div class="col-lg-4">
    <div class="card m-b-30">
        <div class="card-body">
            <div class="media">
                <img class="d-flex mr-3 rounded-circle img-thumbnail thumb-lg" src="{{object.book_phone.avatar.avatar.url}}" alt="{{object.book_phone.avatar.alt}}"/>
                <div class="media-body">
                    <h5 class="mt-0 font-18">{{object.book_phone.name}} {{object.book_phone.last_name}}</h5>
                    <p class="mt-0 text-muted font-14">{{object.book_phone.phone_number}}</p>
                    <p class="mt-0 text-muted font-14">{{object.book_phone.phone_number_1}}</p>
                    <p class="mt-0 text-muted font-14">{{object.book_phone.post}}</p>
                    <ul class="social-links list-inline mb-0">
                        <li style="cursor: pointer;" onclick="delete_item(this)" data-id="{{object.pk}}" class="list-inline-item">
                            <a title data-placement="top" data-toggle="tooltip" class="tooltips">
                                <i style="color:red;" class="fa fa-remove"></i>
                            </a>
                            <span style="color:red;">حذف</span>
                        </li>
                        {% comment %} <li id="EditItem_" class="list-inline-item">
                            <a title data-placement="top" data-toggle="tooltip" class="tooltips" href>
                                <i style="color:blue;" class="fa fa-edit"></i>
                            </a>
                        </li> {% endcomment %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

phone_book/templates/contact_directory.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>دفترچه تلفن</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/bootstrap4.5.min.css' %}" rel="stylesheet">
        <style type="text/css">
    	    body{
                background: #eff3f6;
                margin-top:20px;
            }
            .thumb-lg {
                height: 88px;
                width: 88px;
            }
            .card {
                border: none;
                box-shadow: 1px 0px 20px rgba(0, 0, 0, 0.05);
            }
            .m-b-30 {
                margin-bottom: 30px;
            }
            .social-links li a {
                -webkit-border-radius: 50%;
                background: #fcfdfd;
                border-radius: 50%;
                color: #9f9f9f;
                display: inline-block;
                height: 30px;
                line-height: 30px;
                text-align: center;
                width: 30px;
            }
        </style>
    </head>
    <body>
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" style="cursor: pointer;">
                    <img width="50" src="{{book_owner.avatar.avatar.url}}"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" style="cursor: pointer;">{{book_owner.user.get_full_name}} | {{book_owner.user.username}}<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'phone_book:books' %}">صفحه اصلی</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'phone_book:profile' %}">پروفایل</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:logout'%}">خروج از حساب</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:login'%}">ورود به حساب</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        
        <div class="container">
            <form class="m-2">
                <div class="row">
                    <div class="col-md-4">
                        <label for="PersoneNameID">نام مخاطب</label>
                        <input title="نام را وارد نمایید" required type="text" class="form-control" id="PersoneNameID">
                    </div>
                    <div class="col-md-4">
                        <label for="PersoneLastNameID">نام خانوادگی مخاطب</label>
                        <input title="نام خانوادگی را وارد نمایید" required type="text" class="form-control" id="PersoneLastNameID">
                    </div>
                    <div class="col-md-4">
                        <label for="PersoneAvatarID">آواتار مخاطب</label>
                        <div class="table-responsive">
                            <table>
                                <tr>
                                    {% for avatar in avatars %}
                                    {% if forloop.first %}
                                    <th class="p-0">
                                        <label onclick="bor(this);" for="avatar_{{forloop.counter}}">
                                            <img style="border:1px rgb(50 173 19) solid;" width="50" class="img-thumbnail d-flex mr-5" src="{{avatar.avatar.url}}" alt="{{avatar.alt}}"/>
                                        </label>
                                        <input checked required type="radio" id="avatar_{{forloop.counter}}" name="selectedAvatar" class="d-none" value="{{avatar.pk}}">
                                    </th>
                                    {% else %}
                                    <th class="p-0">
                                        <label onclick="bor(this);" for="avatar_{{forloop.counter}}">
                                            <img style="border:none;" width="50" class="img-thumbnail d-flex mr-5" src="{{avatar.avatar.url}}" alt="{{avatar.alt}}"/>
                                        </label>
                                        <input type="radio" id="avatar_{{forloop.counter}}" name="selectedAvatar" class="d-none" value="{{avatar.pk}}">
                                    </th>
                                    {% endif %}
                                    {% endfor %}
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <label for="PersonePhoneNumberID">شماره همراه مخاطب</label>
                        <input required title="شماره همراه با شروع 09 و 11 رقمی وارد نمایید" pattern="09\d{9}" type="text" class="form-control" id="PersonePhoneNumberID">
                    </div>
                    <div class="col-md-4">
                        <label for="PersonePhoneID">شماره تلفن مخاطب</label>
                        <input title="ابتدا کد شهر سپس شماره را وارد نمایدد" pattern="0\d{15}" type="text" class="form-control" id="PersonePhoneID">
                    </div>
                    <div class="col-md-4">
                        <label for="PersoneJobID">شغل/سمت مخاطب</label>
                        <input type="text" class="form-control" id="PersoneJobID">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6 m-auto">
                        <button onclick="add_phone_book();" type="button" class="btn btn-success btn-block mt-2 mb-2">افزودن مخاطب</button>
                    </div>
                </div>
            </form>
            </hr>
            <div class="row">
                <div class="col-md-8 mb-3">
                    <label for="PersoneSearchID">جستجو مخاطب</label>
                    <input onkeydown="search_item(this);" type="text" class="form-control" id="PersoneSearchID" aria-describedby="PersoneSearch" placeholder="نام یا نام خانوادگی یا بخشی از شماره را وارد نمایید">
                </div>
            </div>
            </hr>
            <div class="row" id="Phone_Books">
                {% include 'AllContacts.html' with object_list=object_list %}
            </div>
            {% csrf_token %}

        </div>
<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script type="text/javascript">

    function search_item(el){
        let element = $(el);
        let query = element.val();
        $.ajax({
            type: 'post',
            url: '/books/search_phone_book',
            data: {
                'query' : query,
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
            },
            //beforeSend: function () {
            //    $("#product_content").html("");
            //},
            success: function (data) {
                $("#Phone_Books").html(data.posts_html) 
            }
        });
    }

    function delete_item(el){
        let element = $(el);
        let el_id = element.data("id");
        $.ajax({
            type: 'post',
            url: '/books/del_phone_book',
            data: {
                'el_id' : el_id,
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
            },
            //beforeSend: function () {
            //    $("#product_content").html("");
            //},
            success: function (data) {
                if(data.status){
                    let Phone_Books = $("#Phone_Books").html(data.posts_html) 
                }
                //else{

                //}
            }
        });
    };
    
    function bor(el){
        let element = $(el);
        $("label > img").css({
            "border": "none"
        });
        element.children().css("border", "1px rgb(50 173 19) solid");
    };

    function add_phone_book() {
        let PersoneName = $("#PersoneNameID").val();
        let PersoneLastName = $("#PersoneLastNameID").val();
        let PersonePhoneNumber = $("#PersonePhoneNumberID").val();
        let PersonePhone = $("#PersonePhoneID").val();
        let PersoneJob = $("#PersoneJobID").val();
        let PersoneAvater = $("input[type='radio'][name='selectedAvatar']:checked").val();
        $.ajax({
            type: 'post',
            url: '/books/add_phone_book',
            data: {
                'name' : PersoneName,
                'last_name' : PersoneLastName,
                'phone_number' : PersonePhoneNumber,
                'phone_number_1' : PersonePhone,
                'post' : PersoneJob,
                'avatar_id' : PersoneAvater,
                'csrfmiddlewaretoken': $('input[name=csrfmiddlewaretoken]').val(),
            },
            //beforeSend: function () {
            //    $("#product_content").html("");
            //},
            success: function (data) {
                if(data.status){
                    let Phone_Books = $("#Phone_Books").html(data.posts_html) 
                }
                //else{

                //}
            }
        });
    }
</script>
</body>
</html>

phone_book/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>پروفایل دفترچه تلفن</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'css/bootstrap4.5.min.css' %}" rel="stylesheet">
        <style type="text/css">
    	    body{
                background: #eff3f6;
                margin-top:20px;
            }
            .thumb-lg {
                height: 88px;
                width: 88px;
            }
            .card {
                border: none;
                box-shadow: 1px 0px 20px rgba(0, 0, 0, 0.05);
            }
            .m-b-30 {
                margin-bottom: 30px;
            }
            .social-links li a {
                -webkit-border-radius: 50%;
                background: #fcfdfd;
                border-radius: 50%;
                color: #9f9f9f;
                display: inline-block;
                height: 30px;
                line-height: 30px;
                text-align: center;
                width: 30px;
            }
        </style>
    </head>
    <body>
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" style="cursor: pointer;">
                    <img width="50" src="{{book_owner.avatar.avatar.url}}"/>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" style="cursor: pointer;">{{book_owner.user.get_full_name}} | {{book_owner.user.username}}<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'phone_book:books' %}">صفحه اصلی</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'phone_book:profile' %}">پروفایل</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:logout'%}">خروج از حساب</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account:login'%}">ورود به حساب</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
        
        <div class="container">
            <div class="row mt-2" id="profile">
                <div class="col-lg-4">
                    <div class="card m-b-30">
                        <div class="card-body">
                            <div class="media">
                                <img class="d-flex mr-3 rounded-circle img-thumbnail thumb-lg" src="{{object.avatar.avatar.url}}" alt="{{object.avatar.alt}}"/>
                                <div class="media-body">
                                    <h5 class="mt-0 font-18">{{object.user.first_name}} {{object.user.last_name}}</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8">
                    <form class="m-2" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="PersoneNameID">نام</label>
                                <input value="{{request.user.first_name}}" title="نام را وارد نمایید" required type="text" class="form-control" name="first_name" id="PersoneNameID">
                            </div>
                            <div class="col-md-4">
                                <label for="PersoneLastNameID">نام خانوادگی</label>
                                <input value="{{request.user.last_name}}" title="نام خانوادگی را وارد نمایید" required type="text" class="form-control" name="last_name"  id="PersoneLastNameID">
                            </div>
                            <div class="col-md-4">
                                <label for="PersoneAvatarID">آواتار</label>
                                <div class="table-responsive">
                                    <table>
                                        <tr>
                                            {% for avatar in avatars %}
                                            {% if forloop.first %}
                                            <th class="p-0">
                                                <label onclick="bor(this);" for="avatar_{{forloop.counter}}">
                                                    <img style="border:1px rgb(50 173 19) solid;" width="50" class="img-thumbnail d-flex mr-5" src="{{avatar.avatar.url}}" alt="{{avatar.alt}}"/>
                                                </label>
                                                <input checked required type="radio" id="avatar_{{forloop.counter}}" name="selectedAvatar" class="d-none" value="{{avatar.pk}}">
                                            </th>
                                            {% else %}
                                            <th class="p-0">
                                                <label onclick="bor(this);" for="avatar_{{forloop.counter}}">
                                                    <img style="border:none;" width="50" class="img-thumbnail d-flex mr-5" src="{{avatar.avatar.url}}" alt="{{avatar.alt}}"/>
                                                </label>
                                                <input type="radio" id="avatar_{{forloop.counter}}" name="selectedAvatar" class="d-none" value="{{avatar.pk}}">
                                            </th>
                                            {% endif %}
                                            {% endfor %}
                                        </tr>
                                    </table>
                                </div>
                            </div>
                            <div class="col-md-6 m-auto">
                                <button type="submit" class="btn btn-success btn-block mt-2 mb-2">ثبت تغییرات</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<script src="{% static 'js/jquery-1.10.2.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script type="text/javascript">
    function bor(el){
        let element = $(el);
        $("label > img").css({
            "border": "none"
        });
        element.children().css("border", "1px rgb(50 173 19) solid");
    };
</script>
</body>
</html>